=== Suvraneel/XMLQuiz/quiz.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="data">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="MCQ" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="question" type="xs:string" />
                            <xs:element name="answer" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="correct">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:enumeration value="y" />
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Suvraneel/XMLQuiz/quiz.xml
<?xml version="1.0" encoding="UTF-8"?><data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="quiz.xsd"><MCQ><question>What is the children prop?</question><answer>A property that lets you pass data to child components</answer><answer correct="y">A property that lets you nest components in other components</answer><answer>A property that adds child values to state</answer><answer>A property that lets you set an object as a property</answer></MCQ><MCQ><question>In which of the following ECMAScript versions was arrow functions introduced in JavaScript?   viz, (params)=>{ return something }</question><answer>ES4</answer><answer correct="y">ES6</answer><answer>ES7</answer><answer>ES8</answer></MCQ><MCQ><question>When rendering a list using the JavaScript `map()` method, what is required for each element rendered?</question><answer correct="y">key</answer><answer>id</answer><answer>data</answer><answer>index</answer></MCQ><MCQ><question>What tool does React use to compile JSX?</question><answer correct="y">Babel</answer><answer>React Router</answer><answer>JSX Compiler</answer><answer>ReactDOM</answer></MCQ><MCQ><question><![CDATA[What props will be available to the following component? <Car {...props} />]]></question><answer>children</answer><answer>only updated ones</answer><answer>only static ones</answer><answer correct="y">all of them</answer></MCQ><MCQ><question>Which of the following are the correct usage of the spread operator and/or method for combining two arrays?</question><answer>const array = [...array1, ...array2];</answer><answer>const array = array1.concat(array2);</answer><answer>array1.push(...array2);</answer><answer correct="y">all of them</answer></MCQ><MCQ><question>React separates the user interface into components. How are components combinded to create a user interface?</question><answer>With webpack</answer><answer correct="y">By nesting components</answer><answer>By putting them in a folder structure</answer><answer>With code splitting</answer></MCQ><MCQ><question>Which of the following is NOT a rule for React Hooks?</question><answer>Hooks can only be called at the top level of a component</answer><answer correct="y">Hooks can be called in Class or Function components</answer><answer>Hooks can only be called inside React Function components</answer><answer>Hooks cannot be conditional</answer></MCQ><MCQ><question>Why should you avoid copying the values of props into a component's state?</question><answer correct="y">Because that would create two instances of the same state that could become out of sync</answer><answer>Because you should never mutate state</answer><answer>Because prop values cannot be stored in state</answer><answer>Because you want to allow data to flow back up to the parent</answer></MCQ><MCQ><question>What is a common use case for ref?</question><answer>To bind the function</answer><answer>To refer to a function</answer><answer correct="y">To directly access a DOM node</answer><answer>To refer to another JavaScript file</answer></MCQ><MCQ><question>Which of the following is a/are benefit of using a CDN (Content delivery network)?</question><answer>Improving website load times</answer><answer>Increasing content availability and redundancy</answer><answer>Reducing bandwidth costs</answer><answer correct="y">All of the above</answer></MCQ><MCQ><question>In React.js, how we can pass the data from one component to another in React.js ?</question><answer>SetState</answer><answer correct="y"> Props</answer><answer>Render with arguments</answer><answer>PropTypes</answer></MCQ><MCQ><question>What is the difference between a functional component and a class component?</question><answer>Functional components are pure functions</answer><answer correct="y">Class components are classes</answer><answer>Functional components are stateless</answer><answer>Class components are stateful</answer></MCQ><MCQ><question>What is Node.JS?</question><answer>Node.js is a web server</answer><answer correct="y"> Node.js is a JavaScript based framework/platform built on Google Chrome'sJavaScript V8 Engine</answer><answer>Node.js is a java based framework</answer><answer>None of the above</answer></MCQ><MCQ><question>Which of the following is true about package.json?</question><answer>package.json is present in the root directory of any Node application/module.</answer><answer>package.json is used to define the properties of a package.</answer><answer>package.json can be used to update dependencies of a Node application.</answer><answer correct="y">All of the above.</answer></MCQ><MCQ><question>Which of the following is true about fs module of Node?</question><answer>Every method in fs module have synchronous as well as asynchronous form.</answer><answer>Asynchronous methods of fs module take last parameter as completion function callback and first parameter of the callback function as error.</answer><answer correct="y">Both of the above.</answer><answer>None of the above.</answer></MCQ><MCQ><question>Which of the following is correct about bootstrap media objects?</question><answer>These are abstract object styles for building various types of components (like blog comments, Tweets, etc.) that feature a left-aligned or right-aligned image alongside the textual content.</answer><answer>The goal of the media object is to make the code for developing these blocks of information drastically shorter.</answer><answer correct="y">Both of the above.</answer><answer>None of the above.</answer></MCQ><MCQ><question>Which of the following command is used to create react-js-app ?</question><answer correct="y">npx create-react-app appname</answer><answer>npm install create-react-app -g</answer><answer>npx install create-react-app -g</answer><answer>install - l create-react-app</answer></MCQ><MCQ><question>What is the default port number in which a React application runs ?</question><answer correct="y">3000</answer><answer>8080</answer><answer>3030</answer><answer>5000</answer></MCQ><MCQ><question>What is the default port number in which a MySqlServer runs ? </question><answer correct="y">3306</answer><answer>8080</answer><answer>3030</answer><answer>3000</answer></MCQ></data>
